package pers.roinflam.futurediary.init;

import pers.roinflam.futurediary.event.FutureEvent;
import pers.roinflam.futurediary.event.bad.*;
import pers.roinflam.futurediary.event.catastrophic.*;
import pers.roinflam.futurediary.event.good.*;

import java.util.ArrayList;
import java.util.List;

public class FutureDiaryEvents {
    public static final List<FutureEvent> EVENTS = new ArrayList<>();
    public static final OverworkEvent OVERWORK_EVENT = new OverworkEvent();
    public static final DequantizationEvent DEQUANTIZATION_EVENT = new DequantizationEvent();
    public static final LightEvent LIGHT_EVENT = new LightEvent();
    public static final BadLuckEvent BAD_LUCK_EVENT = new BadLuckEvent();
    public static final EmotionalEntityEvent EMOTIONAL_ENTITY_EVENT = new EmotionalEntityEvent();
    public static final AbnormalAirPressureEvent ABNORMAL_AIR_PRESSURE_EVENT = new AbnormalAirPressureEvent();
    public static final DisorderAirPressureEvent DISORDER_AIR_PRESSURE_EVENT = new DisorderAirPressureEvent();
    public static final DefileEvent DEFILE_EVENT = new DefileEvent();
    public static final BurnEvent BURN_EVENT = new BurnEvent();
    public static final AcidRainEvent ACID_RAIN_EVENT = new AcidRainEvent();
    public static final ThunderstormEvent THUNDERSTORM_EVENT = new ThunderstormEvent();
    public static final HatredEvent HATRED_EVENT = new HatredEvent();
    public static final SpawnEvent SPAWN_EVENT = new SpawnEvent();
    public static final ThornEvent THORN_EVENT = new ThornEvent();
    public static final SelfExplosionEvent SELF_EXPLOSION_EVENT = new SelfExplosionEvent();
    public static final TriggeringInjuryEvent TRIGGERING_INJURY_EVENT = new TriggeringInjuryEvent();
    public static final TriggeringCrisisEvent TRIGGERING_CRISIS_EVENT = new TriggeringCrisisEvent();
    public static final ConvergentConsumptionEvent CONVERGENT_CONSUMPTION_EVENT = new ConvergentConsumptionEvent();
    public static final LackConvergenceEvent LACK_CONVERGENCE_EVENT = new LackConvergenceEvent();
    public static final AngryEvent ANGRY_EVENT = new AngryEvent();
    public static final InertiaEvent INERTIA_EVENT = new InertiaEvent();
    public static final VampireEvent VAMPIRE_EVENT = new VampireEvent();
    public static final PainSharingEvent PAIN_SHARING_EVENT = new PainSharingEvent();
    public static final EndlessHungerEvent HUNGER_EVENT = new EndlessHungerEvent();
    public static final ProhibitionMagicEvent PROHIBITION_MAGIC_EVENT = new ProhibitionMagicEvent();
    public static final PollutionEvent POLLUTION_EVENT = new PollutionEvent();
    public static final EpidemicsEvent EPIDEMICS_EVENT = new EpidemicsEvent();
    public static final RemodelingEvent REMODELING_EVENT = new RemodelingEvent();
    public static final MingdaoEvent MINGDAO_EVENT = new MingdaoEvent();
    public static final DetailEvent DETAIL_EVENT = new DetailEvent();
    public static final ManiaEvent MANIA_EVENT = new ManiaEvent();
    public static final ArrogantEvent ARROGANT_EVENT = new ArrogantEvent();
    public static final CancerIntensifiesEvent CANCER_INTENSIFIES_EVENT = new CancerIntensifiesEvent();
    public static final TerroristEntityEvent TERRORIST_ENTITY_EVENT = new TerroristEntityEvent();
    public static final DepthDequantizationEvent DEPTH_DEQUANTIZATION_EVENT = new DepthDequantizationEvent();
    public static final BlewUpEvent BLEW_UP_EVENT = new BlewUpEvent();
    public static final SlipperyHandEvent SLIPPERY_HAND_EVENT = new SlipperyHandEvent();
    public static final LostSleepEvent LOST_SLEEP_EVENT = new LostSleepEvent();
    public static final VertigoEvent VERTIGO_EVENT = new VertigoEvent();
    public static final PerceivedLapseEvent PERCEIVED_LAPSE_EVENT = new PerceivedLapseEvent();
    public static final BottomBreakthroughEvent BOTTOM_BREAKTHROUGH_EVENT = new BottomBreakthroughEvent();
    public static final HematopoieticDisordersEvent HEMATOPOIETIC_DISORDERS_EVENT = new HematopoieticDisordersEvent();
    public static final FocusOffsetEvent FOCUS_OFFSET_EVENT = new FocusOffsetEvent();
    public static final BloodBodyVariationEvent BLOOD_BODY_VARIATION_EVENT = new BloodBodyVariationEvent();
    public static final CollapseFearEvent COLLAPSE_FEAR_EVENT = new CollapseFearEvent();
    public static final DeliverySchaleEvent DELIVERY_SCHALE_EVENT = new DeliverySchaleEvent();
    public static final DeadEndEvent DEAD_END_EVENT = new DeadEndEvent();
    public static final AccelerateGrowthEvent ACCELERATE_GROWTH_EVENT = new AccelerateGrowthEvent();
    public static final AdrenalineEvent ADRENALINE_EVENT = new AdrenalineEvent();
    public static final EnhancedMedicalEffectivenessEvent ENHANCED_MEDICAL_EFFECTIVENESS_EVENT = new EnhancedMedicalEffectivenessEvent();
    public static final HappyEndEvent HAPPY_END_EVENT = new HappyEndEvent();
    public static final HardenedArmorEvent HARDENED_ARMOR_EVENT = new HardenedArmorEvent();
    public static final IndustriousEvent INDUSTRIOUS_EVENT = new IndustriousEvent();
    public static final InitiativeEvent INITIATIVE_EVENT = new InitiativeEvent();
    public static final LearnedEvent LEARNED_EVENT = new LearnedEvent();
    public static final LightPowerEvent LIGHT_POWER_EVENT = new LightPowerEvent();
    public static final LonelyWarriorEvent LONELY_WARRIOR_EVENT = new LonelyWarriorEvent();
    public static final LuckyDayEvent LUCKY_DAY_EVENT = new LuckyDayEvent();
    public static final MuteTeamEvent MUTE_TEAM_EVENT = new MuteTeamEvent();
    public static final PantEvent PANT_EVENT = new PantEvent();
    public static final PhotosynthesisEvent PHOTOSYNTHESIS_EVENT = new PhotosynthesisEvent();
    public static final RaidEvent RAID_EVENT = new RaidEvent();
    public static final SpeedThoughtEvent SPEED_THOUGHT_EVENT = new SpeedThoughtEvent();
}
